repos:
-   repo: local
    hooks:
    -   id: check-notebook-outputs
        name: Check Notebook Outputs
        entry: scripts/check_notebooks.sh
        language: script
        files: \.ipynb$
        pass_filenames: true